import type { Metadata } from "next";
import { gql } from "@apollo/client";
import { createApolloClient } from "@/lib/apolloClient";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { cookies } from "next/headers";

import "../globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const GET_NAV_MENU = gql`
  query {
    getNavigationMenu
  }
`;

export const metadata: Metadata = {
  title: "SSR",
  description: "Generated by create next app",
};

export default async function DefaultLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createApolloClient();
  const { data } = await client.query({ query: GET_NAV_MENU });

  const cookieStore = cookies();
  const token = (await cookieStore).get("token")?.value;

  return (
    <html lang="en">
      <body>
        <Header data={data.getNavigationMenu?.header} isSession={token} />
        <main>{children}</main>
        <Footer data={data.getNavigationMenu?.footer} />
      </body>
    </html>
  );
}
