import type { Metadata } from "next";
import AuthHeader from "@/components/AuthHeader/AuthHeader";
import AuthFooter from "@/components/AuthFooter/AuthFooter";
import "../globals.css";

export const metadata: Metadata = {
  title: "SSR",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthHeader />
        <main>{children}</main>
        <AuthFooter />
      </body>
    </html>
  );
}
